# Generated by Django 3.0.7 on 2020-06-07 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='google_login',
            field=models.BooleanField(default=False),
        ),
    ]
