# Generated by Django 3.0.7 on 2020-06-12 15:59

import common.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(null=True, upload_to=common.utils.get_avatar_upload_destination),
        ),
    ]
