# Generated by Django 3.0.5 on 2020-05-22 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='delivery_option',
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='NA', max_length=100),
            preserve_default=False,
        ),
    ]
