# Generated by Django 3.0.5 on 2020-05-23 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_auto_20200523_2109'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
