# Generated by Django 3.0.5 on 2020-05-25 13:42

import common.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_auto_20200525_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(
                upload_to=common.utils.get_product_upload_destination),
        ),
    ]
